server:
   port: 8083

mybatis:
#   config-location: classpath:mybatis/mybatis.cfg.xml        #mybatis配置文件所在路径
   type-aliases-package: com.weixin.entity          #所有Entity别名类所在包
   mapper-locations: classpath:mapper/**/*.xml        #mapper映射文件

spring:
  application: 
    name: send-message
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://crm.jq-taimall.com:3308/cchwechat?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Jqtm88Abc
    type: com.alibaba.druid.pool.DruidDataSource         #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver           #mysql驱动包
    dbcp2:
       min-idle: 5                                 #数据库连接池的最小
       initial-size: 5                             #初始化连接数
       max-total: 5                                #最大连接数
       max-wait-millis: 200                        #等待连接获取的最大超时时间

    